# Generated by Django 6.0 on 2026-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
