# Generated by Django 6.0 on 2025-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_application_resume_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='required_skills',
            field=models.CharField(blank=True, help_text='Skills separated by commas', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Enter skills separated by commas', max_length=500),
        ),
    ]
