# Generated by Django 6.0 on 2026-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_userprofile_academy_name_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='academy_name',
            field=models.CharField(blank=True, help_text='College or University Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief introduction', null=True),
        ),
    ]
