# Generated by Django 6.0 on 2025-12-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_internship_required_skills_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
