# Generated by Django 6.0 on 2025-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_userprofile_department_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='required_skills',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Skills separated by commas', max_length=500),
        ),
    ]
