# Generated by Django 6.0 on 2026-02-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_internship_created_at_userprofile_office_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='external_apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
