# Generated by Django 6.0 on 2026-02-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='external_apply_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
